add_newline = false
palette = "custom"

format = """
[â•­â”€î‚¶](fg:primary)$username[ğŸ­¬](bg:secondary fg:primary)$hostname[ğŸ­¬](bg:primary fg:secondary)$directory[î‚´](fg:primary)$fill[î‚¶](fg:secondary)$shell[ğŸ­®](bg:secondary fg:primary)$time[î‚´](fg:primary)
[â•°â”€](fg:primary)$character
"""

[palettes.custom]
primary = "#8caaee"
secondary = "#9cbbff"
lambda = "#c49bc4"

[username]
format = "[ï€‡ $user ](bg:primary fg:black)"
show_always = true
style_user = "bg:primary fg:black"

[hostname]
format = "[ï„‰ $hostname ](bg:secondary fg:black)"
ssh_only = false

[directory]
format = "[î¾ $path](bg:primary fg:black)[](fg:primary)"
truncation_length = 3
truncate_to_repo = true

[fill]
symbol = "â”€"
style = "fg:primary"

[shell]
format = "[$indicator](bg:secondary fg:black)"
bash_indicator = "bash"
zsh_indicator = "zsh"
fish_indicator = "fish"
disabled = false

[time]
format = "[$time](bg:primary fg:black)[](fg:primary)"
time_format = "%H:%M"
disabled = false

[character]
success_symbol = "[Î»](fg:lambda)"
error_symbol = "[Î»](fg:lambda)"
